root: true

parserOptions:
  sourceType: module
  ecmaVersion: 2021

env:
  browser: true
  node: true
  es2021: true

extends:
  - eslint:recommended
  - prettier
  - ./.eslint-svelte-hacks.js

plugins:
  - svelte3

overrides:
  - files:
      - '*.svelte'
    processor: svelte3/svelte3

rules:
  no-unused-vars:
    - error
    - argsIgnorePattern: ^_
      varsIgnorePattern: ^_

  no-console:
    - error
    - allow:
        - warn
        - error

  no-multiple-empty-lines:
    - error
    - max: 2
      maxEOF: 0

  operator-assignment:
    - error
    - always

  camelcase: error

  no-var: error

  prefer-const:
    - error
    - destructuring: all
