private: yes

scripts:
  # Build Attractions itself into JS files for publishing
  build: pnpm run build
    --dir attractions

  # Run the documentation app locally
  docs:dev: pnpm run dev
    --dir docs

  # Lint everything and attempt auto-fixing
  lint:fix: pnpm run lint-js:fix
    && pnpm run lint-css:fix
    && pnpm run lint-svelte:fix
    && pnpm run lint-format:fix

  # Lint everything without fixing
  lint: pnpm run lint-js
    && pnpm run lint-css
    && pnpm run lint-svelte
    && pnpm run lint-format

  # Export the documentation app into static HTML, CSS and JS
  docs:export: pnpm run export
    --dir docs

  # Build the documentation app for production
  docs:build: pnpm run build
    --dir docs

  lint-js: eslint .
    --ext ".svelte,.js"
    --cache

  lint-js:fix: pnpm run lint-js --
    --fix

  lint-css: stylelint .
    --cache

  lint-css:fix: pnpm run lint-css --
    --fix

  lint-svelte: svelte-check
    --workspace attractions
    --output human
    --fail-on-warnings
    && svelte-check
    --workspace docs
    --output human
    --fail-on-warnings
    --ignore "src/node_modules"

  lint-svelte:fix: svelte-check
    --workspace attractions
    && svelte-check
    --workspace docs
    --ignore "src/node_modules"

  lint-format: prettier .
    --check
    --plugin-search-dir .

  lint-format:fix: prettier .
    --write
    --plugin-search-dir .
    --loglevel warn

  prepare: is-ci || husky install

workspaces:
  - attractions
  - docs

devDependencies:
  '@babel/core': '^7.15.0'
  '@babel/plugin-syntax-dynamic-import': '^7.0.0'
  '@babel/plugin-transform-runtime': '^7.15.0'
  '@babel/preset-env': '^7.15.0'
  '@babel/runtime': '^7.14.8'
  'eslint': '^7.32.0'
  'eslint-config-prettier': '^8.1.0'
  'eslint-plugin-svelte3': '^3.1.2'
  'husky': '^7.0.1'
  'is-ci': '^3.0.0'
  'lint-staged': '^11.1.2'
  'prettier': '^2.3.2'
  'prettier-plugin-svelte': '^2.3.0'
  'stylelint': '^13.11.0'
  'stylelint-config-prettier': '^8.0.2'
  'stylelint-config-sass-guidelines': '^8.0.0'
  'stylelint-config-standard': '^22.0.0'
  'svelte': '^3.42.1'
  'svelte-check': '^2.2.4'
  'typescript': '^4.3.2'
