name: Release
on:
  release:
    types: [published]

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: docs
    name: Deploy docs to Pages
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install and Build 🔧
        run: |
          yarn install
          SAPPER_APP_BASEPATH=attractions yarn export --basepath attractions

      - name: Deploy demo to GitHub Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/__sapper__/export/attractions/
          force_orphan: true
  release:
    runs-on: ubuntu-latest
    name: Release to npm
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          registry-url: https://registry.npmjs.org/
      - name: Install and Build 🔧
        run: |
          cp README.md LICENSE attractions/
          cd attractions
          yarn install
          yarn build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
